"""initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-07-05 10:32:09.935602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector — required by the embedding columns added further down (added via
    # raw SQL, not through the ORM: pgvector's Vector type isn't autogenerate-friendly)
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m1_worlds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('world_doc', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('element_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('character_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('relationship_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('world_base_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('graph_id', sa.String(length=255), nullable=True),
    sa.Column('graph_ontology', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('graph_status', sa.String(length=20), nullable=False),
    sa.Column('graph_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_character_id', sa.UUID(), nullable=True),
    sa.Column('snapshot_generation', sa.Integer(), server_default='0', nullable=False),
    sa.Column('scale', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_character_id'], ['m2_characters.id'], name='fk_m1worlds_user_character_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_m1_worlds_user_id', 'm1_worlds', ['user_id'], unique=False)
    op.create_table('m21_admin_config',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('group_name', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=True),
    sa.Column('plain_value', sa.Text(), nullable=True),
    sa.Column('iv', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_name', 'key', name='uq_m21_admin_config_group_key')
    )
    op.create_table('m23_guide_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('all_content', sa.Text(), server_default='', nullable=False),
    sa.Column('recent_content', sa.Text(), server_default='', nullable=False),
    sa.Column('recent_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('context_help', sa.Text(), server_default='{}', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m9_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_email', 'm9_users', ['email'], unique=False)
    op.create_index('idx_users_username', 'm9_users', ['username'], unique=False)
    op.create_table('m10_api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('api_format', sa.String(length=20), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('encrypted_key', sa.Text(), nullable=False),
    sa.Column('iv', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['m9_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('m16_welcome_quotes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('ai_verdict', sa.String(length=20), nullable=True),
    sa.Column('ai_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['m9_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_m16_quotes_status', 'm16_welcome_quotes', ['status'], unique=False)
    op.create_index('idx_m16_quotes_user_id', 'm16_welcome_quotes', ['user_id'], unique=False)
    op.create_table('m20_matterbridge_bindings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('api_url', sa.Text(), nullable=False),
    sa.Column('api_token_encrypted', sa.Text(), nullable=False),
    sa.Column('api_token_iv', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['m1_worlds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id')
    )
    op.create_table('m25_element_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('element_id', sa.String(length=128), nullable=False),
    sa.Column('element_type', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=True),
    sa.Column('tier', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['m1_worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_m25_world_elem', 'm25_element_embeddings', ['world_id', 'element_id'], unique=True)
    op.create_index('idx_m25_world_id', 'm25_element_embeddings', ['world_id'], unique=False)

    # tsv (full-text) + embedding (pgvector) — raw SQL, see models.py comment
    op.execute("ALTER TABLE m25_element_embeddings ADD COLUMN tsv tsvector")
    op.execute("ALTER TABLE m25_element_embeddings ADD COLUMN embedding vector(1024) NOT NULL")
    op.execute("CREATE INDEX idx_m25_tsv ON m25_element_embeddings USING GIN(tsv)")
    op.execute(
        "CREATE INDEX idx_m25_embedding ON m25_element_embeddings "
        "USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
    )

    op.create_table('m26_event_index',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('dissemination', sa.Float(), nullable=False),
    sa.Column('core_participants', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('effective_day', sa.Integer(), nullable=True),
    sa.CheckConstraint('dissemination >= 0 AND dissemination <= 1', name='ck_m26_event_index_dissemination_range'),
    sa.ForeignKeyConstraint(['world_id'], ['m1_worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_m26_event_index_world_id', 'm26_event_index', ['world_id'], unique=False)
    op.create_table('m2_characters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('portrait_url', sa.Text(), nullable=True),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('graph_node_uuid', sa.String(length=255), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['m1_worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_m2_characters_world_id', 'm2_characters', ['world_id'], unique=False)
    op.create_table('m2_world_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('synced_generation', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['parent_version_id'], ['m2_world_versions.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['m1_worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_m2_world_versions_world_id', 'm2_world_versions', ['world_id'], unique=False)
    op.create_table('m3_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_key_event', sa.Boolean(), nullable=False),
    sa.Column('user_marked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['m1_worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_m3_events_status', 'm3_events', ['world_id', 'status'], unique=False)
    op.create_table('m8_discord_bindings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('guild_id', sa.Text(), nullable=False),
    sa.Column('channel_daily', sa.Text(), nullable=True),
    sa.Column('channel_event', sa.Text(), nullable=True),
    sa.Column('channel_chat', sa.Text(), nullable=True),
    sa.Column('narrator_webhook_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['m1_worlds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id')
    )
    op.create_table('m2_relations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('character_a', sa.UUID(), nullable=False),
    sa.Column('character_b', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('historical_changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('graph_edge_uuid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['character_a'], ['m2_characters.id'], ),
    sa.ForeignKeyConstraint(['character_b'], ['m2_characters.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['m1_worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_m2_relations_world_id', 'm2_relations', ['world_id'], unique=False)
    op.create_index('uq_m2_relations_active', 'm2_relations', ['character_a', 'character_b', 'direction'], unique=True, postgresql_where="status = 'active'")
    op.create_table('m4_chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('participant_mode', sa.String(length=10), nullable=True),
    sa.Column('memories_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=True),
    sa.Column('last_flushed_sequence', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['m2_world_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id'], ['m1_worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_m4_chat_sessions_world_id', 'm4_chat_sessions', ['world_id'], unique=False)
    op.create_table('m8_character_webhooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('webhook_id', sa.Text(), nullable=False),
    sa.Column('webhook_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['m2_characters.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['m1_worlds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id')
    )
    op.create_index('idx_m8_char_webhooks_world', 'm8_character_webhooks', ['world_id'], unique=False)
    op.create_table('m2_character_memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('memory_type', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('visible_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('origin_event_id', sa.UUID(), nullable=True),
    sa.Column('is_hearsay', sa.Boolean(), nullable=False),
    sa.Column('propagated_from', sa.UUID(), nullable=True),
    sa.Column('involved_characters', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('propagation_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hop_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('info_amount', sa.Float(), nullable=True),
    sa.Column('source_character_id', sa.UUID(), nullable=True),
    sa.Column('memory_sequence', sa.Integer(), nullable=True),
    sa.Column('event_name', sa.String(length=255), nullable=True),
    sa.Column('perspective_detail', sa.Text(), nullable=True),
    sa.Column('reflection', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=20)), nullable=True),
    sa.Column('dissemination', sa.Float(), nullable=True),
    sa.Column('memory_category', sa.String(length=20), nullable=True),
    sa.Column('short_term_reflection', sa.Text(), nullable=True),
    sa.CheckConstraint('dissemination IS NULL OR (dissemination >= 0 AND dissemination <= 1)', name='ck_m2_character_memories_dissemination_range'),
    sa.CheckConstraint('hop_count >= 0 AND hop_count <= 2', name='ck_m2_memories_hop_count_range'),
    sa.CheckConstraint('info_amount IS NULL OR (info_amount >= 0 AND info_amount <= 1)', name='ck_m2_memories_info_amount_range'),
    sa.ForeignKeyConstraint(['character_id'], ['m2_characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origin_event_id'], ['m3_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['propagated_from'], ['m2_characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['m4_chat_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_character_id'], ['m2_characters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['world_id'], ['m1_worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_m2_character_memories_character_id', 'm2_character_memories', ['character_id'], unique=False)
    op.create_index('idx_m2_character_memories_event_name', 'm2_character_memories', ['character_id', 'event_name'], unique=False, postgresql_where=sa.text('event_name IS NOT NULL'))
    op.create_index('idx_m2_character_memories_world_id', 'm2_character_memories', ['world_id'], unique=False)

    # embedding (pgvector) — raw SQL, see models.py comment; only short-term,
    # non-hearsay memories get embedded, hence nullable + the partial HNSW index
    op.execute("ALTER TABLE m2_character_memories ADD COLUMN embedding vector(1024)")
    op.execute(
        "CREATE INDEX idx_m2_memory_embedding ON m2_character_memories "
        "USING hnsw (embedding vector_cosine_ops) "
        "WITH (m = 16, ef_construction = 64) "
        "WHERE memory_type = 'short_term' AND is_hearsay = false"
    )

    # Hearsay / short-term memory helper indexes (raw SQL — not declared as
    # SQLAlchemy Index() objects in models.py, so autogenerate can't see them)
    op.execute(
        "CREATE INDEX idx_m2_memories_hearsay ON m2_character_memories "
        "(character_id, visible_at DESC) WHERE is_hearsay = true"
    )
    op.execute(
        "CREATE INDEX idx_m2_memories_short_term_real ON m2_character_memories "
        "(character_id, created_at DESC) WHERE memory_type = 'short_term' AND is_hearsay = false"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_m2_memories_session_hearsay ON m2_character_memories "
        "(character_id, session_id, propagated_from) "
        "WHERE is_hearsay = true AND session_id IS NOT NULL AND origin_event_id IS NULL"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_m2_memories_event_hearsay ON m2_character_memories "
        "(character_id, origin_event_id) "
        "WHERE is_hearsay = true AND origin_event_id IS NOT NULL"
    )

    op.create_table('m4_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('sender_type', sa.String(length=20), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('real_time', sa.DateTime(), nullable=False),
    sa.Column('is_key_message', sa.Boolean(), nullable=False),
    sa.Column('user_participated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='normal', nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['m4_chat_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id'], ['m1_worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_m4_messages_sender', 'm4_messages', ['sender_id'], unique=False)
    op.create_index('uq_m4_messages_session_sequence', 'm4_messages', ['session_id', 'sequence'], unique=True, postgresql_where='session_id IS NOT NULL AND sequence IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_m4_messages_session_sequence', table_name='m4_messages', postgresql_where='session_id IS NOT NULL AND sequence IS NOT NULL')
    op.drop_index('idx_m4_messages_sender', table_name='m4_messages')
    op.drop_table('m4_messages')
    op.drop_index('idx_m2_character_memories_world_id', table_name='m2_character_memories')
    op.drop_index('idx_m2_character_memories_event_name', table_name='m2_character_memories', postgresql_where=sa.text('event_name IS NOT NULL'))
    op.drop_index('idx_m2_character_memories_character_id', table_name='m2_character_memories')
    op.drop_table('m2_character_memories')
    op.drop_index('idx_m8_char_webhooks_world', table_name='m8_character_webhooks')
    op.drop_table('m8_character_webhooks')
    op.drop_index('idx_m4_chat_sessions_world_id', table_name='m4_chat_sessions')
    op.drop_table('m4_chat_sessions')
    op.drop_index('uq_m2_relations_active', table_name='m2_relations', postgresql_where="status = 'active'")
    op.drop_index('idx_m2_relations_world_id', table_name='m2_relations')
    op.drop_table('m2_relations')
    op.drop_table('m8_discord_bindings')
    op.drop_index('idx_m3_events_status', table_name='m3_events')
    op.drop_table('m3_events')
    op.drop_index('idx_m2_world_versions_world_id', table_name='m2_world_versions')
    op.drop_table('m2_world_versions')
    op.drop_index('idx_m2_characters_world_id', table_name='m2_characters')
    op.drop_table('m2_characters')
    op.drop_index('idx_m26_event_index_world_id', table_name='m26_event_index')
    op.drop_table('m26_event_index')
    op.drop_index('idx_m25_world_id', table_name='m25_element_embeddings')
    op.drop_index('idx_m25_world_elem', table_name='m25_element_embeddings')
    op.drop_table('m25_element_embeddings')
    op.drop_table('m20_matterbridge_bindings')
    op.drop_index('idx_m16_quotes_user_id', table_name='m16_welcome_quotes')
    op.drop_index('idx_m16_quotes_status', table_name='m16_welcome_quotes')
    op.drop_table('m16_welcome_quotes')
    op.drop_table('m10_api_keys')
    op.drop_index('idx_users_username', table_name='m9_users')
    op.drop_index('idx_users_email', table_name='m9_users')
    op.drop_table('m9_users')
    op.drop_table('m23_guide_content')
    op.drop_table('m21_admin_config')
    op.drop_index('idx_m1_worlds_user_id', table_name='m1_worlds')
    op.drop_table('m1_worlds')
    # ### end Alembic commands ###
